-- 质量数据平台的两张表(ADR-022)。全部 IF NOT EXISTS,应用每次启动执行一遍,已有卷 / 新卷都能用。
CREATE TABLE IF NOT EXISTS qa_test_run (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    batch_no        VARCHAR(64)     NOT NULL COMMENT '批次号,唯一:CI 的 run id 或本地时间戳',
    suite           VARCHAR(32)     NOT NULL COMMENT 'unit / api / security / all',
    source          VARCHAR(32)     NOT NULL DEFAULT 'local' COMMENT 'ci / local',
    commit_sha      VARCHAR(64)     NULL,
    branch          VARCHAR(128)    NULL,
    started_at      DATETIME(3)     NOT NULL,
    duration_ms     BIGINT UNSIGNED NOT NULL DEFAULT 0,
    total           INT UNSIGNED    NOT NULL,
    passed          INT UNSIGNED    NOT NULL,
    failed          INT UNSIGNED    NOT NULL DEFAULT 0,
    skipped         INT UNSIGNED    NOT NULL DEFAULT 0,
    xfailed         INT UNSIGNED    NOT NULL DEFAULT 0,
    pass_rate       DECIMAL(6,2)    NOT NULL COMMENT 'passed / (total - skipped - xfailed) * 100',
    line_coverage   DECIMAL(6,2)    NULL COMMENT '行覆盖率 %',
    branch_coverage DECIMAL(6,2)    NULL COMMENT '分支覆盖率 %',
    coverage_source VARCHAR(32)     NULL COMMENT 'jacoco / coverage.py',
    note            VARCHAR(500)    NULL,
    created_at      DATETIME(3)     NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_test_run_batch (batch_no),
    KEY idx_test_run_suite_started (suite, started_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='测试执行记录';

CREATE TABLE IF NOT EXISTS qa_perf_run (
    id              BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    tag             VARCHAR(64)     NOT NULL COMMENT '轮次标识,唯一,与 tests/perf/results/<tag> 对应',
    scenario        VARCHAR(32)     NOT NULL COMMENT 'create / grab / read / grab_race ...',
    threads         INT UNSIGNED    NOT NULL,
    duration_s      INT UNSIGNED    NOT NULL DEFAULT 0,
    samples         INT UNSIGNED    NOT NULL,
    qps             DECIMAL(10,2)   NOT NULL,
    avg_ms          DECIMAL(10,2)   NULL,
    p50_ms          INT UNSIGNED    NULL,
    p95_ms          INT UNSIGNED    NULL,
    p99_ms          INT UNSIGNED    NOT NULL,
    max_ms          INT UNSIGNED    NULL,
    error_rate      DECIMAL(6,3)    NOT NULL DEFAULT 0 COMMENT '错误率 %',
    commit_sha      VARCHAR(64)     NULL,
    executed_at     DATETIME(3)     NOT NULL,
    env_json        JSON            NOT NULL COMMENT '压测前的环境状态快照(tests/perf/tools/env_state.py --json 的输出):池、堆、GC、后台任务、数据量、MySQL 配置、MQ 积压',
    baseline        TINYINT(1)      NOT NULL DEFAULT 0 COMMENT '1 = 该 scenario+threads 的当前基线',
    note            VARCHAR(500)    NULL,
    created_at      DATETIME(3)     NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_perf_run_tag (tag),
    KEY idx_perf_run_scenario (scenario, threads, executed_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='压测轮次(带环境状态)';
